application: flightpin
version: 1
runtime: python
api_version: 1

handlers:
# begin static handlers
## Images for static pages
- url: /www/images
  static_dir: www/images

## CSS for static pages
- url: /www/stylesheets
  static_dir: www/stylesheets

## scripts for static pages
- url: /www/scripts
  static_dir: www/scripts

## scripts for data
- url: /www/data
  static_dir: www/data

- url: .*
  script: flightpin.py

## Image exentensions
##- url: /(.*\.(gif|png|jpg))
##  static_files: static/\1
##  upload: static/(.*\(gif|png|jpg))


